name: dev_stories
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.20.0
  image: ^4.3.0
  image_picker: ^1.1.2
  image_picker_windows: ^0.2.1+1
  camera: ^0.11.0+2
  camera_windows: ^0.2.6+1
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/dicoding_story_logo.png